<?php

use Illuminate\Database\Seeder;

class StudentDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('student_details')->delete();
        
        \DB::table('student_details')->insert(array (
            0 => 
            array (
                'user_id' => 5,
                'house_no' => '2131',
                'street' => 'Kanto',
                'barangay_id' => 1,
                'district_id' => 1,
                'birthday' => '1999-05-06',
                'birthplace' => 'Parola',
                'religion' => 'Cathilic',
                'gender' => 0,
                'brothers' => 1,
                'sisters' => 1,
                'batch_id' => 1,
                'application_date' => '2017-06-10 00:00:00',
                'first_essay' => 'Hey',
                'second_essay' => 'Hey 2',
                'organization' => 'Bantay bata',
                'position' => 'Chairman',
                'participation_date' => '1231',
                'remarks' => NULL,
                'application_status' => 'Pending',
                'student_status' => 'Continuing',
                'is_renewal' => 0,
                'is_steps_done' => 0,
            ),
            1 => 
            array (
                'user_id' => 6,
                'house_no' => '2131',
                'street' => 'Kanto',
                'barangay_id' => 1,
                'district_id' => 1,
                'birthday' => '1999-06-06',
                'birthplace' => 'Manila',
                'religion' => 'Asasnfas',
                'gender' => 0,
                'brothers' => 2,
                'sisters' => 2,
                'batch_id' => 1,
                'application_date' => '2017-06-10 00:00:00',
                'first_essay' => 'Asfafasfgsagfk',
                'second_essay' => 'Asfashflahfasjflhas',
                'organization' => 'Ksafhasflh',
                'position' => 'Asfhaskjfh',
                'participation_date' => '1231',
                'remarks' => NULL,
                'application_status' => 'Accepted',
                'student_status' => 'Continuing',
                'is_renewal' => 0,
                'is_steps_done' => 0,
            ),
            2 => 
            array (
                'user_id' => 7,
                'house_no' => '2131',
                'street' => 'Tondo',
                'barangay_id' => 2,
                'district_id' => 2,
                'birthday' => '1999-06-07',
                'birthplace' => 'Manila',
                'religion' => 'Catholic',
                'gender' => 0,
                'brothers' => 0,
                'sisters' => 1,
                'batch_id' => 1,
                'application_date' => '2017-06-10 00:00:00',
                'first_essay' => 'Asfasfxxxx',
                'second_essay' => 'Xxxxxxx',
                'organization' => 'Org',
                'position' => 'Pres',
                'participation_date' => '2313',
                'remarks' => NULL,
                'application_status' => 'Pending',
                'student_status' => 'Continuing',
                'is_renewal' => 0,
                'is_steps_done' => 0,
            ),
            3 => 
            array (
                'user_id' => 8,
                'house_no' => '1231',
                'street' => 'Tatalon',
                'barangay_id' => 2,
                'district_id' => 2,
                'birthday' => '1999-06-08',
                'birthplace' => 'Quezon',
                'religion' => 'Catholic',
                'gender' => 0,
                'brothers' => 2,
                'sisters' => 2,
                'batch_id' => 1,
                'application_date' => '2017-06-10 00:00:00',
                'first_essay' => 'Momosss',
                'second_essay' => 'Lloslsllss',
                'organization' => 'Bantaysss',
                'position' => 'House dog',
                'participation_date' => '1231',
                'remarks' => NULL,
                'application_status' => 'Pending',
                'student_status' => 'Continuing',
                'is_renewal' => 0,
                'is_steps_done' => 0,
            ),
            4 => 
            array (
                'user_id' => 9,
                'house_no' => '1231',
                'street' => 'Saflsjfkj',
                'barangay_id' => 1,
                'district_id' => 1,
                'birthday' => '1999-06-08',
                'birthplace' => 'Asfjhasfjk',
                'religion' => 'Hajfkhashfj',
                'gender' => 0,
                'brothers' => 12,
                'sisters' => 2,
                'batch_id' => 1,
                'application_date' => '2017-06-10 00:00:00',
                'first_essay' => 'Acxxq',
                'second_essay' => 'Asfassasasf',
                'organization' => 'Safjlhafkahjkx',
                'position' => 'Shfalfh',
                'participation_date' => '1231',
                'remarks' => NULL,
                'application_status' => 'Pending',
                'student_status' => 'Continuing',
                'is_renewal' => 0,
                'is_steps_done' => 0,
            ),
            5 => 
            array (
                'user_id' => 10,
                'house_no' => '2131',
                'street' => 'Ajhfkasfjkhgajfhag',
                'barangay_id' => 2,
                'district_id' => 2,
                'birthday' => '1999-06-02',
                'birthplace' => 'Safsafhjkg',
                'religion' => 'Khgsakfgaskhg',
                'gender' => 0,
                'brothers' => 1,
                'sisters' => 2,
                'batch_id' => 1,
                'application_date' => '2017-06-10 00:00:00',
                'first_essay' => 'Asfsafsafasf',
                'second_essay' => 'Fsafsafsaasf',
                'organization' => 'Asfasf',
                'position' => 'Asfkgasfhjg',
                'participation_date' => '1231',
                'remarks' => NULL,
                'application_status' => 'Pending',
                'student_status' => 'Continuing',
                'is_renewal' => 0,
                'is_steps_done' => 0,
            ),
            6 => 
            array (
                'user_id' => 11,
                'house_no' => '1231',
                'street' => 'Asfjkafkjsfjh',
                'barangay_id' => 1,
                'district_id' => 1,
                'birthday' => '1999-06-07',
                'birthplace' => 'Safjasfhajkh',
                'religion' => 'Fhafjksakschajk',
                'gender' => 1,
                'brothers' => 1,
                'sisters' => 1,
                'batch_id' => 1,
                'application_date' => '2017-06-10 00:00:00',
                'first_essay' => 'Sasxxxafasfsa',
                'second_essay' => 'Assgaxgasgwgwa',
                'organization' => 'Sasafsaf',
                'position' => 'Asasfs',
                'participation_date' => '1231',
                'remarks' => NULL,
                'application_status' => 'Pending',
                'student_status' => 'Continuing',
                'is_renewal' => 0,
                'is_steps_done' => 0,
            ),
            7 => 
            array (
                'user_id' => 12,
                'house_no' => '2131',
                'street' => 'Fjafhkasfhasfhj',
                'barangay_id' => 2,
                'district_id' => 2,
                'birthday' => '1999-06-07',
                'birthplace' => 'Asfsfsafg',
                'religion' => 'Hjkghgfahjagfh',
                'gender' => 0,
                'brothers' => 1,
                'sisters' => 2,
                'batch_id' => 1,
                'application_date' => '2017-06-10 00:00:00',
                'first_essay' => 'Csamcaicmasicn',
                'second_essay' => 'Asfasfasfsge',
                'organization' => 'Asfasfhgafhgasfg',
                'position' => 'Asfasfasfs',
                'participation_date' => '1231',
                'remarks' => NULL,
                'application_status' => 'Pending',
                'student_status' => 'Continuing',
                'is_renewal' => 0,
                'is_steps_done' => 0,
            ),
            8 => 
            array (
                'user_id' => 13,
                'house_no' => '2131',
                'street' => 'Kjshfgsafhjasfhjkgasefg',
                'barangay_id' => 2,
                'district_id' => 2,
                'birthday' => '1999-06-08',
                'birthplace' => 'Asfghjkfghjs',
                'religion' => 'Ghjgjkhgsfhsa',
                'gender' => 1,
                'brothers' => 1,
                'sisters' => 2,
                'batch_id' => 1,
                'application_date' => '2017-06-10 00:00:00',
                'first_essay' => 'Sfasfhjafjkfk',
                'second_essay' => 'Safasfasfsa',
                'organization' => 'Askfjasfhkashj',
                'position' => 'Asfasfhsahfg',
                'participation_date' => '2131',
                'remarks' => NULL,
                'application_status' => 'Pending',
                'student_status' => 'Continuing',
                'is_renewal' => 0,
                'is_steps_done' => 0,
            ),
            9 => 
            array (
                'user_id' => 14,
                'house_no' => '2131',
                'street' => 'Masfmisfnasfas',
                'barangay_id' => 1,
                'district_id' => 1,
                'birthday' => '1999-06-06',
                'birthplace' => 'Manila',
                'religion' => 'Cathloic',
                'gender' => 1,
                'brothers' => 1,
                'sisters' => 1,
                'batch_id' => 1,
                'application_date' => '2017-06-11 00:00:00',
                'first_essay' => 'Sagcksahgcsakgcywajsgc',
                'second_essay' => 'Asgkhjfgaksjgfkjxhsa',
                'organization' => 'Safkgfkhg',
                'position' => 'Asgfkjasfghskjg',
                'participation_date' => '1231',
                'remarks' => NULL,
                'application_status' => 'Accepted',
                'student_status' => 'Continuing',
                'is_renewal' => 0,
                'is_steps_done' => 0,
            ),
            10 => 
            array (
                'user_id' => 24,
                'house_no' => '1231',
                'street' => 'Kjhasflhasvjh',
                'barangay_id' => 1,
                'district_id' => 1,
                'birthday' => '1999-06-07',
                'birthplace' => 'Lolcss',
                'religion' => 'Askhca',
                'gender' => 0,
                'brothers' => 1,
                'sisters' => 1,
                'batch_id' => 1,
                'application_date' => '2017-06-12 12:24:45',
                'first_essay' => 'Sscacsacac',
                'second_essay' => 'Ascascsacas',
                'organization' => 'Scaklcsh',
                'position' => 'Skahcj',
                'participation_date' => '2131',
                'remarks' => NULL,
                'application_status' => 'Accepted',
                'student_status' => 'Continuing',
                'is_renewal' => 0,
                'is_steps_done' => 0,
            ),
            11 => 
            array (
                'user_id' => 25,
                'house_no' => '1231',
                'street' => 'Ksachakjhcsacajhc',
                'barangay_id' => 1,
                'district_id' => 1,
                'birthday' => '1999-06-07',
                'birthplace' => 'Csaasc',
                'religion' => 'Assasac',
                'gender' => 0,
                'brothers' => 11,
                'sisters' => 22,
                'batch_id' => 1,
                'application_date' => '2017-06-12 19:02:23',
                'first_essay' => 'Sfsacashashclkj',
                'second_essay' => 'Sacascascas',
                'organization' => 'Acsasc',
                'position' => 'Acsasca',
                'participation_date' => '1997',
                'remarks' => NULL,
                'application_status' => 'Pending',
                'student_status' => 'Continuing',
                'is_renewal' => 0,
                'is_steps_done' => 0,
            ),
        ));
        
        
    }
}