<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'type' => 'Admin',
                'first_name' => 'Marvin',
                'middle_name' => 'Magdasoc',
                'last_name' => 'Damiano',
                'email' => 'admin@gmail.com',
                'password' => '$2y$10$vHTvCpjxB.0MeMWsD/xJWe3w1nG/yA2TBWXGS/SDizs2hMNlmiSX6',
                'cell_no' => '1234567891234',
                'picture' => 'Default.png',
                'is_active' => 1,
                'last_login' => '2017-06-12 17:52:25',
                'remember_token' => 'r8NmRBlPlpXC5ZRZaUWmYu7WDASOMVYxyPTuRnjchcPU6KKbnpSuUTS2iVlX',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'type' => 'Coordinator',
                'first_name' => 'Christopher',
                'middle_name' => 'Ramos',
                'last_name' => 'Atienza',
                'email' => 'coordinator@gmail.com',
                'password' => '$2y$10$/qMP5odICGPADYLFallTnu3BNFZH58yQpSCXaqIFx42YH1q9sj8qa',
                'cell_no' => '213131311312312',
                'picture' => '6a764bbaf165b8b63cf27f0c99512575.jpg',
                'is_active' => 1,
                'last_login' => '2017-06-12 17:54:38',
                'remember_token' => '6HqSHqYF2bTilvYkHhUOAMW6lEFxqcdhOuLZmmvTfitJwgsUIvCCmaSdFTAe',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'type' => 'Coordinator',
                'first_name' => 'Bryan',
                'middle_name' => NULL,
                'last_name' => 'Buenavides',
                'email' => 'coordinator2@gmail.com',
                'password' => '$2y$10$50Tp93x074g8lYmG0Y5JreowDR3MUp5RbMPBx7T9KBf64vwBt20sC',
                'cell_no' => '111111111111111',
                'picture' => 'Default.png',
                'is_active' => 1,
                'last_login' => '2017-06-10 21:10:53',
                'remember_token' => 'G0HhgkqF7bHMGZm8WkHORoANgCzmEWhXJEl8lbcz8pGPJZoFKY90e3j4AMh8',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'type' => 'Admin',
                'first_name' => 'Joshua',
                'middle_name' => 'Padilla',
                'last_name' => 'Siano',
                'email' => 'admin2@gmail.com',
                'password' => '$2y$10$vxhR7y7objWC399/5AqF2Owudrr1zP7iZrbzJ8mORD5NJsnyYblDO',
                'cell_no' => '1234567891234',
                'picture' => 'Default.png',
                'is_active' => 1,
                'last_login' => '2017-06-10 12:42:58',
                'remember_token' => 'k94WD5KNGH11NaJKsOfbXcUQ7NawrFziMAS0xG3gfwFNexdpAJrjz7C3wSZn',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'type' => 'Student',
                'first_name' => 'Marife',
                'middle_name' => 'Magdasoc',
                'last_name' => 'Damiano',
                'email' => 'student@gmail.com',
                'password' => '$2y$10$Uhs1qj9ozXzDo5EA1j9teOKU6SgWBhWlg4pJTx6N3HxBa4b7VjI02',
                'cell_no' => '12312312313',
                'picture' => '41bebc7c311724613268a74eebb79c00.jpg',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'type' => 'Student',
                'first_name' => 'Pablo',
                'middle_name' => 'Pura',
                'last_name' => 'Damiano',
                'email' => 'student2@gmail.com',
                'password' => '$2y$10$3SA6lldHzLzfuKfsfWFub.QqSnOoBQUkrWLf8BYpXQYHD2klE9DsK',
                'cell_no' => '123131312313121',
                'picture' => '20ccae3e0e6fbbd599edfb939a37e6c0.jpg',
                'is_active' => 1,
                'last_login' => '2017-06-12 17:54:56',
                'remember_token' => 'It67YYE4ljSHi21adBWCb0ecejw9y9rcgtbJBKPavRfsVdKB8IPKCvAMGvqL',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'type' => 'Student',
                'first_name' => 'Gerald',
                'middle_name' => 'Constantino',
                'last_name' => 'Ramos',
                'email' => 'student3@gmail.com',
                'password' => '$2y$10$lftPVD4rlo0cJU7c5oo9keemupvMyMxaK5rilZmTVgA8JcLsj5tTW',
                'cell_no' => '123131312321312',
                'picture' => '2396e89de8ae5ec911eaf41485091393.jpg',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'type' => 'Student',
                'first_name' => 'Alfred',
                'middle_name' => 'Berlo',
                'last_name' => 'Tingson',
                'email' => 'student4@gmail.com',
                'password' => '$2y$10$kIZ/9syfoI.VgULWwHkI9OV7qohCmbJtZktL97YjDKF2r3nlCTL6u',
                'cell_no' => '1231231232131',
                'picture' => '06430258354d6a73690489dc6c507631.jpg',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'type' => 'Student',
                'first_name' => 'Neil',
                'middle_name' => 'Angelo',
                'last_name' => 'Pereyra',
                'email' => 'student5@gmail.com',
                'password' => '$2y$10$GHBWg7Un5yvHptBPodN9WeZekQFcdDxvXB8x.70JL37Hy/g2T9XIi',
                'cell_no' => '213123132123213',
                'picture' => 'fea427b34ad09e38610c0f0c35981fc8.png',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'type' => 'Student',
                'first_name' => 'Tyron',
                'middle_name' => NULL,
                'last_name' => 'Delos reyes',
                'email' => 'student6@gmail.com',
                'password' => '$2y$10$1jW8dJJGEYRt7jDO8b.oOOAKM97VKQnGSMp1BnEc0kXmZxznmTT1C',
                'cell_no' => '123123131231232',
                'picture' => 'd994a736ba307e0368a4173d6f2981da.jpg',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'type' => 'Student',
                'first_name' => 'Angela',
                'middle_name' => 'Nicole',
                'last_name' => 'Clara',
                'email' => 'student7@gmail.com',
                'password' => '$2y$10$XTh6CqFshUP/GGr3pQs8NO/2oEy1k/heGKSRfs1aDEN8zYzHyI4h2',
                'cell_no' => '123123123123123',
                'picture' => 'cc536edffc7ace2a78bb47c38e78fd80.jpg',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'type' => 'Student',
                'first_name' => 'Kate',
                'middle_name' => NULL,
                'last_name' => 'Juvida',
                'email' => 'student8@gmail.com',
                'password' => '$2y$10$fXoH06ycXOplcouLPJrMuOmRZO/AxqEChzEDi3no/qq5kKqj6MNwi',
                'cell_no' => '21312312231231',
                'picture' => 'e245962a4c5806d06c485d17c9fea75d.jpg',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'type' => 'Student',
                'first_name' => 'Angela',
                'middle_name' => NULL,
                'last_name' => 'Saclapus',
                'email' => 'student9@gmail.com',
                'password' => '$2y$10$Z68un1YdseQgShBURh/niupi4Z6l873pHLzCppfX252gcdsPKyAEO',
                'cell_no' => '213121231231312',
                'picture' => '9592f776ed8fcde57a0cb6f8d6b86cca.jpg',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'type' => 'Student',
                'first_name' => 'Maria',
                'middle_name' => 'Mercedes',
                'last_name' => 'California',
                'email' => 'student10@gmail.com',
                'password' => '$2y$10$pGrS.4t8Ru2ecf8e7by6eORdohS9Vuwa215irhXf6tZ9ScR7lVSxu',
                'cell_no' => '213123123123123',
                'picture' => '62b9e338f8027808ea5b7287189c7ef5.jpg',
                'is_active' => 1,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'type' => 'Coordinator',
                'first_name' => 'ZsmgvjT5GHsA9WC',
                'middle_name' => 'ZsmgvjT5GHsA9WC',
                'last_name' => 'ZsmgvjT5GHsA9WC',
                'email' => 'coordinator3@gmail.com',
                'password' => '$2y$10$bgNWFAyazRNLuFJ8Iqoi5uTQGPrHAMEy7OynsMiB2N42YYN4w6R0G',
                'cell_no' => 'ZsmgvjT5GHsA9WC',
                'picture' => 'Default.png',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'type' => 'Coordinator',
                'first_name' => 'he3rjTv7TMVuTeP',
                'middle_name' => 'he3rjTv7TMVuTeP',
                'last_name' => 'he3rjTv7TMVuTeP',
                'email' => 'coordinator4@gmail.com',
                'password' => '$2y$10$KEy7J/Y3e4nlhgWUj5mjtuCnW2r7KSpWc3wnT31MiDRc6vcnkMUsy',
                'cell_no' => 'he3rjTv7TMVuTeP',
                'picture' => 'Default.png',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'type' => 'Coordinator',
                'first_name' => 'Lu6IGBX2U5MiT94',
                'middle_name' => 'Lu6IGBX2U5MiT94',
                'last_name' => 'Lu6IGBX2U5MiT94',
                'email' => 'coordinator5@gmail.com',
                'password' => '$2y$10$OVIeoudQ1Kl1CukNkS6kUu02CGiVq3Yt5slPffP/B4OHTUKZJHH1W',
                'cell_no' => 'Lu6IGBX2U5MiT94',
                'picture' => 'Default.png',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'type' => 'Coordinator',
                'first_name' => 'DgKbfXDz34QnxEt',
                'middle_name' => 'DgKbfXDz34QnxEt',
                'last_name' => 'DgKbfXDz34QnxEt',
                'email' => 'coordinator6@gmail.com',
                'password' => '$2y$10$OaIxNg85KIdfyeqTooBMzeKoqNCbAJGaVkL7F3cEuXJ8dPBxkUerq',
                'cell_no' => 'DgKbfXDz34QnxEt',
                'picture' => 'Default.png',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'type' => 'Coordinator',
                'first_name' => 'YQsH4FUqRl07smg',
                'middle_name' => 'YQsH4FUqRl07smg',
                'last_name' => 'YQsH4FUqRl07smg',
                'email' => 'coordinator7@gmail.com',
                'password' => '$2y$10$vdh7t0cacipIZrDfpn6Coe1Yca7k8Duoqjkow5bEstrtZCdxVMgI2',
                'cell_no' => 'YQsH4FUqRl07smg',
                'picture' => 'Default.png',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'type' => 'Coordinator',
                'first_name' => 'DiOzyqz3o7IBU5d',
                'middle_name' => 'DiOzyqz3o7IBU5d',
                'last_name' => 'DiOzyqz3o7IBU5d',
                'email' => 'coordinator8@gmail.com',
                'password' => '$2y$10$Eg9c.PraDfr917bdn5HCaeju61jU1ZfwgL6D8PNvF05ePbIHcVIxq',
                'cell_no' => 'DiOzyqz3o7IBU5d',
                'picture' => 'Default.png',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'type' => 'Coordinator',
                'first_name' => '7RJhzSeidVtEjsY',
                'middle_name' => '7RJhzSeidVtEjsY',
                'last_name' => '7RJhzSeidVtEjsY',
                'email' => 'coordinator9@gmail.com',
                'password' => '$2y$10$LyU7s7owZR33joJM/xTs4eIMeiH34NVLwWJptXr5j625MF/NSvFtC',
                'cell_no' => '7RJhzSeidVtEjsY',
                'picture' => 'Default.png',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'type' => 'Coordinator',
                'first_name' => 'FIqAPhUOWH38miV',
                'middle_name' => 'FIqAPhUOWH38miV',
                'last_name' => 'FIqAPhUOWH38miV',
                'email' => 'coordinator10@gmail.com',
                'password' => '$2y$10$yMQH.SDa1a52Io7VyNCeEOj33owfsGpJ2X8ZPm6pFJxfylvYH/FA.',
                'cell_no' => 'FIqAPhUOWH38miV',
                'picture' => 'Default.png',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'type' => 'Coordinator',
                'first_name' => 'IQlJNcyK4mZU4OO',
                'middle_name' => 'IQlJNcyK4mZU4OO',
                'last_name' => 'IQlJNcyK4mZU4OO',
                'email' => 'coordinator11@gmail.com',
                'password' => '$2y$10$yVhObtidfPO1G/0dK7NuHeuvvzcxkJmUYNT64I8Qjza48UwFACE.2',
                'cell_no' => 'IQlJNcyK4mZU4OO',
                'picture' => 'Default.png',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'type' => 'Student',
                'first_name' => 'Lol',
                'middle_name' => 'Mide',
                'last_name' => 'Posl',
                'email' => 'student11@gmail.com',
                'password' => '$2y$10$hWKNEAxhpK8/0mhHKXCrCOvis9W399byO0.RULuFlEbWCcFoM1Uxi',
                'cell_no' => '123123123123213',
                'picture' => '7df93ee0ca8e41e7ff9b66ee1c1c7f04.png',
                'is_active' => 1,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'type' => 'Student',
                'first_name' => 'Hcjshsjk',
                'middle_name' => 'Hsacjhashj',
                'last_name' => 'Klhaschkjh',
                'email' => 'student12@gmail.com',
                'password' => '$2y$10$Fx7HJzBCRdPRIQZPu91HEONDaqcIDMGBR/rIWhm/IzuIPENSa13RK',
                'cell_no' => '213131312312313',
                'picture' => '4fa2c5e92fe4b5e6ca9dd41e9a7c7b94.jpg',
                'is_active' => 0,
                'last_login' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}